import type { Metadata } from "next";
import { Barlow,Open_Sans } from "next/font/google";
import "./globals.css";
import { ProposalProvider } from "./contexts/ProposalsContext";
import { Web3Modal } from './contexts/Web3ModalContext'
import { ProviderProvider } from './contexts/ProviderContext'
import Navbar from "./components/Navbar";

const barlow = Barlow({ 
  subsets: ["latin"] ,
  weight: [
  "100", 
  "200", 
  "300", 
  "400",
  "500",
  "600",
  "700",
  "800",
  "900"
]
});

const openSans = Open_Sans({ 
  subsets: ["latin"] ,
  weight: [
  "300", 
  "400",
  "500",
  "600",
  "700",
  "800"
]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Web3Modal>
      <ProviderProvider>
        <ProposalProvider>
          <html lang="en" className={`${barlow.className} ${openSans.className}`}>
            <head>
              <link rel="icon" href="./od-circle.svg" />
              <title>Open Dollar Governance Proposals</title>
            </head>
            <body className={barlow.className}>
              <Navbar/>
              {children}
            </body>
          </html>
        </ProposalProvider>
      </ProviderProvider>
    </Web3Modal>
  );
}
